spring:
  application:
    name: mall-gateway
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.135.1:8848

    gateway:
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
        - id: user_route   #路由ID，全局唯一，建议配置服务名
          uri: lb://mall-user  #lb 整合负载均衡器ribbon,loadbalancer
          predicates:
            - Path=/user/**   # 断言，路径相匹配的进行路由

        - id: order_route  #路由ID，全局唯一，建议配置服务名
          uri: lb://mall-order  #lb 整合负载均衡器ribbon,loadbalancer
          predicates:
            - Path=/order/**   # 断言，路径相匹配的进行路由
          filters:
            - AddRequestHeader=X-Request-Color,blue #添加请求头
            - AddRequestParameter=book,Java-Programming # 添加请求参数，不能有空格
            - CheckAuth=Q10Viking,Love-Java-Programming # 自定义过滤器